<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Framework</a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li><a href="<?php echo APP_URL; ?>">Inicio</a></li>
				<!--<li><a href="">Servicios</a></li>
				<li><a href="">Productos</a></li>
				<li><a href="">Nosotros</a></li>
				<li><a href="">Contacto</a></li>-->
				<li><a href="<?php echo APP_URL."/users/"; ?>">Usuarios</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li><a href="<?php echo APP_URL."/users/logout"; ?>">Cerrar sesión</a></li>
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</nav>